sudo: true
dist: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K $encrypted_d57dcd0eac94_key -iv $encrypted_d57dcd0eac94_iv
  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername --setalias CI_HubOrg
- chmod 777 testCodeCoverage.sh
- chmod 777 jq-linux64
script:
- sfdx force:org:create --targetdevhubusername CI_HubOrg --definitionfile config/project-scratch-def.json
  --setalias CI_SO --setdefaultusername
- sfdx force:source:push -u CI_SO
- sfdx force:apex:test:run -u CI_SO -c -r human --verbose
- ./testCodeCoverage.sh
- sfdx force:org:delete -u CI_SO -p
